### PR TITLE
Home screen

### PR DESCRIPTION
**Pull request by r6097**
There is a bundle error due to the import path in StackNavigator.js saying "blogs/" when the project folder is named "Blogs", I think the branches can merge if that is fixed in the main branch.
The Home screen should be functional with a gallery of motivational images, info about the organization, and a quiz

### CODE REVIEW

**Review by RSadaq — CHANGES_REQUESTED** [review]
You've done a great job on this so far. I've got a few requests: 

1. Please add a bar at top of page, under HOME header. Background colour: firebrick. White-coloured text (in italics) to read: ‘Improving bodies and minds in sport. By teens, for teens’. Add animation so text is constantly sliding to the right. Also a little stick figure image running in front of the text would be great.

2. Images: a. Are you able to add a subtle overlay which tells user to swipe images?
b. Kobe Bryant image is a little grainy - it'd be great if you could swap this one.

3. Quiz: I've made some minor changes to this so questions & answers should now read as follows:

1. The mind is the initial driver for anything you want to accomplish. True 
2. ‘Preparation’ is the tactic where you see mental images to prepare yourself for competition. False. Correct answer = This is called ‘visualization’.
3. Goal setting helps keep you prepared. True
4. Intrinsic motivation can be caused by a desire to play the sport. True
5. ‘Sense of coherence’ is a personal orientation that expresses the way an individual responds to stress. True
6. Strength gives you the ability to overcome obstacles. False. Correct answer = Confidence does.
7. Sport psychology focuses on the concerns of the elite athlete. False. Correct answer = It is for athletes at all levels.
8. Excellent decision-making is the result of months of practice in the environment. True
9. ‘Physical attributes’ is a tip in sport psychology that can be applied to real life. True
10. Freud said, “You have the power over your mind; not outside events. Realize this and you will find strength”. True
11. Our goal is to teach young athletes the proper way to develop a good mentality. True
12. Motivation is the reason for someone acting in a particular way. True

If the user clicks the wrong answer, a pop up needs to appear/message on screen informing them of the correct answer (for each question). In cases where the answer is ‘true’ but the user clicked ‘false’, the message simply needs to be ‘This is actually true!’.

Ensure score doesn’t go into negative numbers. It’d also be great if the score was displayed as, ‘how many the user has correct’ out of 12’.

4. Our story: 

Let’s get rid of the text AFTER the sentence, ‘Unlike other organizations, Mind-Design Sports is designed by teens, for teens and kids’.
White background for this section with royal blue text (like the blue used on MDS website).


5. Our mission: 

Please DELETE, ‘Mind-Design Sports hopes that their platform will bring greater awareness to the sport psychology, hoping that their brand becomes well-known by all young athletes’.
Transparent sports image behind 'Our mission' text. Text color: black.

Lastly, please add adequate white spacing between images, our story, our mission & quiz. Titles 'Our Story' & 'Our mission' need to be a little larger/more prominent.

Thanks.

**Review by RSadaq — CHANGES_REQUESTED** [review]
Looks so much better. Just a couple of things that were missed: 

1. Images: a. Are you able to add a subtle overlay which tells user to swipe images? 
b. Kobe Bryant image is a little grainy - it'd be great if you would swap this one.

2. White space below ‘Our mission’ section before quiz and after quiz.

3. Please double-check the quiz works properly -  a congrats msg comes up with score when the quiz is not actually finished & spacing between the true/false buttons changes a few times. 
 
Great that you corrected the answer on Freud’s quote, the iOS app had this one as true when it isn’t -  so well done for picking up on this! Please note that i also removed the question about folding paper (the 12 qus should be the ones I put on the last review).
Each question needs a number so user knows which number they are on.

*Additionally, I’d like to see the screen with the text in the bar at the top static (Text will have to be reduced in size so it fits on the screen) - so I can make a decision on which is better.

*Text for 'our story' & 'our mission' to be aligned to the centre please.

*Lastly, will you please optimize all the images used on the HomeScreen? They need to be about 20/25KB each, if possible.

Thanks very much & keep up the good work:)

**Comment by RSadaq** [comment]
Thank you for making the changes Robert. A few minor things which need fixing before we can merge this branch into the main: 

1. The Marcus Aurelius image/quote flashes when it is swiped.
2. Question number 10 on the quiz, the True False buttons suddenly lose the spacing between them & it comes back for qu 11.
3. The quiz looked better without the space above, so please revert back to no spacing between it & 'Our mission' section.

Many thanks.

**Comment by r6097** [comment]
Hey, I haven't been able to replicate the issue where Marcus Aurelius image/quote flashes, so I couldn't fix it

**Review by RSadaq — APPROVED** [review]

**Comment by RSadaq** [comment]
Hi Robert, your pull request is causing conflicts in: 
constants/index.js
navigation/StackNavigator.js
package-lock.json

So that I can merge your branch into the main, will you please create a new pull request without checking these files in? Also, with the 'blogs' folder, it needs to be lower case. Lastly, before you do any more work, please do a git fetch so your local code is up to date. Thanks & job well done on the Home screen 👍

**Pull request closed without merging**
